// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | pal16
//    output | layers
//    input  | base_layer_icon.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_base_layer_icon_length;
extern const uint8_t  gfx_base_layer_icon[1257];
