#define TAPPING_TERM 280
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define CAPS_WORD_INVERT_ON_SHIFT

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_TIMEOUT 120000
#endif // RGB_MATRIX_ENABLE
